### PR TITLE
Chore(Player bridge): Added custom configuration to player bridge

### PR DESCRIPTION
**Pull request by reuvenlevitsky**
## Description:

Added custom configuration to player bridge

### Checklist for this pull request

* [x] PR is scoped to one task
* [ ] Tests are included
* [ ] Documentation included
* [ ] One of:
  * [x] The PR is not making any UI change
  * [ ] The PR is making a UI change but not a product change
    * [ ] Screenshots included

Thank you!

### CODE REVIEW

**Review by lomudi — APPROVED** [review]
💯

**Comment by BoazWarshawsky** [comment]
Hi @reuvenlevitsky, sorry for the question but I wonder if this is a functionality in the level of the developers only or ZAPP/Support?
where is that configuration located? we should rebuild after changing it?

**Comment by reuvenlevitsky** [comment]
Developers only. JS and native devs. The configuration comes from JS - React native.

**Comment by BoazWarshawsky** [comment]
thanks @reuvenlevitsky

**Pull request merged**
