### PR TITLE
chore: circle conf file added

### PR DESCRIPTION
**Pull request by dickie81**
## Description:
Allows tests to run on Circle CI

### Checklist for this pull request

* [x] PR is scoped to one task
* [x] Tests are included
* [x] Documentation included
* [x] One of:
  * [x] The PR is not making any UI change
  * [ ] The PR is making a UI change but not a product change
    * [ ] Screenshots included

Thank you!

### CODE REVIEW

**Review by francois-codes — CHANGES_REQUESTED** [review]
Please use CircleCI 2.0 :) @Budaa can show you an example

**Comment by dickie81** [comment]
Upgraded to version 2. Please re-review.

**Review by francois-codes — CHANGES_REQUESTED** [review]
We should leverage cache for check out and installing dependencies, you can find examples here : 
https://github.com/applicaster/zapp/blob/master/.circleci/config.yml

next step is tagging / publishing to npm, but maybe you want to tackle that in another PR ?

**Comment by dickie81** [comment]
@f-roland Caching added. I would like to tackle publishing in a new PR as this is valuable in itself.

**Review by francois-codes — APPROVED** [review]

**Comment by francois-codes** [comment]
good addition 👍 nice

**Pull request merged**
