### PR TITLE
Bump NPM package version to 1.0.1 to take changes into effect when publishing.

### PR DESCRIPTION
**Pull request by pintocarlos**

### CODE REVIEW

**Review by lomudi — DISMISSED** [review]
💯 
@pintocarlos if we will remove the "@applicaster/" in the name it will make it public NPM, right?
I think this should be public, what do you say?

**Comment by pintocarlos** [comment]
@lomudi corretct the prefix `@applicaster` makes it private
The interfaces in this library are only compatible with our infrastructure.
You mean to make it public so 3rd party can download and have these tools for building RN apps on our platform?

**Comment by lomudi** [comment]
yup @pintocarlos, to make it public in order to make it easier for 3rd party developers to build react native plugins for Zapp.

**Comment by pintocarlos** [comment]
@lomudi please approve and I'll merge and publish it.

**Review by lomudi — APPROVED** [review]
:100:

**Comment by pintocarlos** [comment]
I am unable to publish:
npm ERR! you must verify your email before publishing a new package: https://www.npmjs.com/email-edit :react-native-zapp-bridge

Who has access to technical@applicaster.com ? An email confirmation needs to be verified @lomudi

**Comment by lomudi** [comment]
@pintocarlos I didn't got a confirmation email. if i remember right also @ranmeirman have access.

**Pull request merged**
