### PR TITLE
add documentation for getting plugin custom configuration

### PR DESCRIPTION
**Pull request by eladkariti2**

### CODE REVIEW

**Comment by lomudi** [comment]
@eladkariti2 it does not require also a JS class to handle it? only docs?

**Comment by eladkariti2** [comment]
@lomudi it is unnecessary to add a code that will wrap it, i use the approach as the Zapp player and Zapp login. 
The implementation is in the native code.

**Comment by lomudi** [comment]
@eladkariti2 it was done also on iOS?

**Comment by eladkariti2** [comment]
@lomudi  yes, but we are going to make some changes in Android to  be align with IOS plugin implementation . it will be merge after the changes.

**Comment by lomudi** [comment]
@eladkariti2 if it is not relevant anymore let's close this one. thx.

**Pull request closed without merging**
